/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardForm: typeof import('./src/components/CardForm.vue')['default']
    CardMovie: typeof import('./src/components/CardMovie.vue')['default']
    FilterBar: typeof import('./src/components/FilterBar.vue')['default']
    ListMovies: typeof import('./src/components/ListMovies.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
